// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdCe2jV_7LczSz24vrpkiZGagXnblXv0',
    appId: '1:37613061673:web:164efde5c3883370cbfe38',
    messagingSenderId: '37613061673',
    projectId: 'shopitem-b2de4',
    authDomain: 'shopitem-b2de4.firebaseapp.com',
    storageBucket: 'shopitem-b2de4.firebasestorage.app',
    measurementId: 'G-1J0435TW08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWQ7sRG6nHXtMikm-Ti965ESR2EeYZHU',
    appId: '1:37613061673:android:6eb876bd94db5bb0cbfe38',
    messagingSenderId: '37613061673',
    projectId: 'shopitem-b2de4',
    storageBucket: 'shopitem-b2de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQhYj7awsTnGvy7CQ-T7_9t-WjaRPi5Y',
    appId: '1:37613061673:ios:6c3c0ba03204a960cbfe38',
    messagingSenderId: '37613061673',
    projectId: 'shopitem-b2de4',
    storageBucket: 'shopitem-b2de4.firebasestorage.app',
    iosBundleId: 'com.example.shopitem',
  );
}
